### ISSUE TITLE
Cannot load crypto/ed25519 when building go-waku

### ISSUE THREAD

**Issue by oskarth** [status-im/go-waku#17]
Following the README and running `make` I get:

```
...
go: extracting golang.org/x/text v0.3.5
build command-line-arguments: cannot load crypto/ed25519: cannot find module providing package crypto/ed25519
make: *** [Makefile:6: build] Error 1
```

```
> go version
go version go1.12.5 linux/amd64
```

Guessing either some version requirement, or some dependency management that is needed. Didn't debug, just tried following README for all Waku implementations :)

cc @richard-ramos

**Comment by richard-ramos** [comment]
Your go version is ancient (released in 2019/05/06 https://golang.org/doc/devel/release.html#go1.12.minor),  after installing it i ran into the same issue. I tried then with go1.13.10 which is 1y old, and it did compile. I'd suggest upgrading go to a more recent version like 1.16.3

**Comment by oskarth** [comment]
Works, dope chat2 UI!

Maybe worth specifying minimal/recommended required Go version in the README?

**Comment by richard-ramos** [comment]
Good idea!
