### ISSUE TITLE
In mobile, Error packaging iOS。

### ISSUE THREAD

**Issue by Dzhijian** [status-im/go-waku#227]
hello,I am using  "gomobile bind-v-target = ios-ldflags =" -s-w "github.com/status-im/go-waku/mobile" in mobile, Error packaging iOS。

/var/folders/c7/yby2ndzd2h3908d6sdy6szw00000gn/T/gomobile-work-3488408587/ios/pkg/mod/github.com/elastic/gosigar@v0.12.0/sigar_darwin.go:12:10: fatal error: 'libproc.h' file not found

Can you tell me how to solve this problem。

github.com/libp2p/go-libp2p-nat
github.com/gorilla/websocket
github.com/opentracing/opentracing-go
github.com/cruxic/go-hmac-drbg/hmacdrbg
github.com/lucas-clemente/quic-go/logging
# github.com/elastic/gosigar
/var/folders/c7/yby2ndzd2h3908d6sdy6szw00000gn/T/gomobile-work-3488408587/ios/pkg/mod/github.com/elastic/gosigar@v0.12.0/sigar_darwin.go:12:10: fatal error: 'libproc.h' file not found
#include <libproc.h>
         ^~~~~~~~~~~
1 error generated.
github.com/status-im/go-waku/waku/v2/utils
github.com/golang/protobuf/proto
github.com/opentracing/opentracing-go/ext
github.com/lucas-clemente/quic-go/internal/congestion
github.com/lucas-clemente/quic-go/internal/handshake
github.com/lucas-clemente/quic-go/internal/logutils
github.com/ipfs/go-log/tracer
github.com/ethereum/go-ethereum/p2p/nat
github.com/lucas-clemente/quic-go/internal/ackhandler
github.com/status-im/go-discover/discover/v4wire
github.com/libp2p/go-ws-transport
github.com/status-im/go-discover/discover/v5wire
github.com/ipfs/go-log
go.opencensus.io/resource
go.opencensus.io/metric/metricdata
github.com/lucas-clemente/quic-go
github.com/status-im/go-discover/discover
go.opencensus.io/tag
go.opencensus.io/metric/metricproducer
github.com/libp2p/go-libp2p-discovery
github.com/status-im/go-waku/waku/v2/protocol/swap
go.opencensus.io/stats/internal
golang.org/x/mobile/internal/mobileinit
go.opencensus.io/stats
github.com/libp2p/go-libp2p-pubsub
github.com/golang/protobuf/ptypes
github.com/prometheus/client_model/go
github.com/matttproud/golang_protobuf_extensions/pbutil
github.com/status-im/go-waku-rendezvous/pb
github.com/prometheus/client_golang/prometheus/internal
github.com/prometheus/common/expfmt
github.com/status-im/go-waku/waku/v2/protocol/pb
github.com/status-im/go-waku-rendezvous
github.com/prometheus/client_golang/prometheus
github.com/status-im/go-waku/waku/v2/discv5
# golang.org/x/mobile/internal/mobileinit
/var/folders/c7/yby2ndzd2h3908d6sdy6szw00000gn/T/gomobile-work-3488408587/ios/pkg/mod/golang.org/x/mobile@v0.0.0-20190719004257-d2bd2a29d028/internal/mobileinit/mobileinit_ios.go:22:2: warning: 'asl_log' is deprecated: first deprecated in iOS 10.0 - os_log(3) has replaced asl(3) [-Wdeprecated-declarations]
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS15.4.sdk/usr/include/asl.h:586:5: note: 'asl_log' has been explicitly marked deprecated here
go.opencensus.io/stats/view
github.com/status-im/go-waku/waku/v2/protocol
github.com/status-im/go-waku/waku/persistence
github.com/status-im/go-waku/waku/v2
github.com/status-im/go-waku/waku/v2/metrics
golang.org/x/mobile/bind/seq
github.com/status-im/go-waku/waku/v2/protocol/filter
github.com/status-im/go-waku/waku/v2/protocol/store
github.com/status-im/go-waku/waku/v2/protocol/relay
github.com/libp2p/go-tcp-transport
github.com/lucas-clemente/quic-go/qlog
github.com/status-im/go-waku/waku/v2/protocol/lightpush
github.com/multiformats/go-multiaddr-dns
github.com/libp2p/go-libp2p-quic-transport
github.com/libp2p/go-libp2p/p2p/protocol/circuitv2/relay
github.com/libp2p/go-libp2p/p2p/host/relaysvc
github.com/libp2p/go-libp2p/p2p/host/basic
github.com/libp2p/go-libp2p/p2p/host/autorelay
github.com/libp2p/go-libp2p/config
gomobile: ios/arm64: go build -v -ldflags -s -w -buildmode=c-archive -o /var/folders/c7/yby2ndzd2h3908d6sdy6szw00000gn/T/gomobile-work-3488408587/gowaku-ios-arm64.a ./gobind failed: exit status 2

**Comment by richard-ramos** [comment]
Should be fixed in latest master. The solution is to use this fork of go-watchdog in go.mod
```
replace github.com/raulk/go-watchdog v1.2.0 => github.com/status-im/go-watchdog v1.2.0-ios-nolibproc
```
