### ISSUE TITLE
DNS discovery URL is required

### ISSUE THREAD

**Issue by fryorcraken** [status-im/go-waku#293]
```
▶ ./build/waku --dns-discovery true --dns-discovery-url enrtree://ANTL4SLG2COUILKAPE7EF2BYNL2SHSHVCHLRD5J7ZJLN5R3PRJD2Y@prod.waku.nodes.status.im
2022-08-25T11:33:15.006+1000	FATAL	gowaku	DNS discovery URL is required	{"node": "16Uiu2HAm1dFXFfmf1usCLEBozVHPRj4krca3JtkzEipWHetz2QGq"}
```

The discovery URL is provided...

**Comment by fryorcraken** [comment]
Ah, I see it works with `=` but how come `dns-discovery` was detected without `=` but not `--dns-discovery-url`?

**Comment by richard-ramos** [comment]
Flags should be set using `=`, not spaces. `--dns-discovery` worked because When you type a boolean flag, and don't specify its value, it's assumed to be true (i.e. `--dns-discovery=true`)

**Comment by fryorcraken** [comment]
Thanks :)
