### ISSUE TITLE
Waku Message timestamp is not in seconds

### ISSUE THREAD

**Issue by D4nte** [status-im/go-waku#41]
# Problem

The [spec](https://rfc.vac.dev/spec/14/) says:

> The timestamp field MAY be filled out to signify the time at which the message is generated by its sender. This field holds the Unix epoch time. Omitting it means the timestamp is unspecified.
> [...]
> `double timestamp = 4;`

So the timestamp is the _Unix epoch time_ and is a float double.

My interpretation is that it represent _seconds_ as _Unix epoch time_ is usually in seconds.

Trying to get clarification: https://github.com/vacp2p/rfc/issues/438

My observation is that go-waku sends nanoseconds

- js-waku timestamp (seconds): `1627541233.767`
- go-waku timestamp (from richard): `1627423791245469200`
- nim-waku timestamp uses [`epochTimes`](https://nim-lang.org/docs/times.html#epochTime) which seems to return seconds: 

https://github.com/status-im/nim-waku/blob/6b1e0c30791c9bd7614978f18c450564e794ca0f/tests/v2/test_message_store.nim#L19

# Solution

As per https://github.com/vacp2p/rfc/issues/438

**Comment by richard-ramos** [comment]
Fixed in https://github.com/status-im/go-waku/commit/fd49e33a45e8913eaeb2eca17f75088577e98882
