### ISSUE TITLE
Inconsistent naming of flags compared to Nim-Waku

### ISSUE THREAD

**Issue by jakubgs** [status-im/go-waku#80]
While working on the Ansible role for `go-waku` I found a few inconsistencies in flag naming compared to `nim-waku`:

* `--dbpath` instead of `--db-path`
* `--metrics*` instead of `--metrics-server*` (I think the shorter name is better tbh)
* `--port`  but no `--address`
* `--ws-port` but no `--ws-address`
* `--no-relay` instead of `--relay`
* `--store-node` instead of `--storenode` ~~(might be better changed in `nim-waku`)~~
* `--filter-node` instead of `--filternode` ~~(might be better changed in `nim-waku`)~~
* `--lightpush-node` instead of `--lightpushnode` ~~(might be better changed in `nim-waku`)~~

Not a huge issue, but it's good to keep things consistent, especially since we are implementing the same spec.

**Comment by jakubgs** [comment]
@richard-ramos is this going to be addressed? I wanted to simplify enabling protocols in the Ansible role, but I can't because of the inconsistent flag naming like `--no-relay`. It would be some much simpler and cleaner if it was `--relay=false` and `--relay=true`.

**Comment by richard-ramos** [comment]
I'll try to get it done tomorrow

**Comment by jakubgs** [comment]
Thank you.

**Comment by D4nte** [comment]
Also `--address` and `--listen-address`.
`--rpc-admin` is not defined.

@richard-ramos do you want a new issue?

**Comment by richard-ramos** [comment]
@D4nte 
Created https://github.com/status-im/go-waku/issues/231 and https://github.com/status-im/go-waku/issues/232 for the missing RPC APIs

**Comment by richard-ramos** [comment]
@D4nte 
`--address` and `--listen-address` are now available in latest master

**Comment by richard-ramos** [comment]
@D4nte 
`--rpc-admin` and `--rpc-private` were just added to latest master
