### ISSUE TITLE
No flat to provide public address to node

### ISSUE THREAD

**Issue by jakubgs** [status-im/go-waku#82]
The `nim-waku` node supports a `--nat` flag which can be specified like this: `--nat=extip:12.34.56.78`

No such flag is available in `go-waku`, and at startup I see this in the logs:
```
2021-10-14T17:12:55.275Z#011INFO#011basichost#011basic/natmgr.go:91#011DiscoverNAT error:no NAT found
```

**Comment by richard-ramos** [comment]
Fixed in latest master. An option --address was added that let's you specify the IP address to listen to. (By default go-waku will listen in 0.0.0.0)
